name: C# Code Analysis

on:
  push:
    branches:
      - main  

jobs:
  code_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # замените '6.0.x' на соответствующую версию .NET SDK

      - name: Change directory to OP.PRACTICAL_WORK_7/OP.PRACTICAL_WORK_7
        run: cd OP.PRACTICAL_WORK_7/OP.PRACTICAL_WORK_7

      - name: Install StyleCop.Analyzers
        run: dotnet add package StyleCop.Analyzers --version 1.1.118

      - name: Restore NuGet packages
        run: dotnet restore OP.PRACTICAL_WORK_7/OP.PRACTICAL_WORK_7.sln

      - name: Run StyleCop.Analyzers
        run: dotnet build OP.PRACTICAL_WORK_7/OP.PRACTICAL_WORK_7.sln --no-incremental
