# pipeline.yaml

stages:
  - name: syntax_check
    jobs:
      - name: check_csharp_syntax
        steps:
          - name: checkout_code
            script: echo "Checking out code"
          - name: compile_code
            script: |
              csc.exe /t:library temp.cs
              exit_code=$?
              if [ $exit_code -eq 0 ]; then
                echo "Compilation successful"
              else
                echo "Compilation failed with exit code $exit_code"
                exit 1
              fi
          - name: check_syntax
            script: echo "Syntax check passed"
